# Generated by Django 5.1.5 on 2025-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
