# Generated by Django 5.1.5 on 2025-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0016_rename_satus_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('neck', models.CharField(blank=True, max_length=50, null=True)),
                ('bust', models.FloatField(blank=True, max_length=100, null=True)),
                ('waist', models.FloatField(blank=True, max_length=100, null=True)),
                ('hips', models.FloatField(blank=True, max_length=100, null=True)),
                ('length', models.FloatField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
