# Generated by Django 5.1.4 on 2025-03-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0018_customdressorder_delete_tbl_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdressorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online.tbl_register'),
        ),
    ]
