# Generated by Django 5.1.4 on 2025-03-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0019_customdressorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdressorder',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
