# Generated by Django 5.1.4 on 2025-03-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0020_customdressorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='d_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='p_date',
            field=models.DateTimeField(null=True),
        ),
    ]
