# Generated by Django 5.1.5 on 2025-03-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0023_customdressorder_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
