# render.yaml  – keep everything else the same
services:
  - type: web
    name: online_boutique
    env: python
    buildCommand: |
      pip install -r requirements.txt
    releaseCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn boutique.wsgi:application --bind 0.0.0.0:$PORT
