# Generated by Django 5.1.5 on 2025-03-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_contact',
        ),
        migrations.RemoveField(
            model_name='tbl_productvariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='tbl_Cart',
        ),
        migrations.DeleteModel(
            name='tbl_Register',
        ),
        migrations.DeleteModel(
            name='tbl_category_add',
        ),
        migrations.DeleteModel(
            name='tbl_Product',
        ),
        migrations.DeleteModel(
            name='tbl_ProductVariant',
        ),
    ]
