# Generated by Django 5.1.4 on 2025-03-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0013_tbl_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
