# Generated by Django 5.1.5 on 2025-03-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0014_orderitem_color_orderitem_image_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='satus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
