# Generated by Django 5.1.5 on 2025-03-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0015_order_satus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='satus',
            new_name='status',
        ),
    ]
