# Generated by Django 5.1.4 on 2025-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0017_tbl_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_name', models.CharField(max_length=255)),
                ('fabric', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('neck_design', models.CharField(max_length=100)),
                ('custom_neck_design', models.CharField(blank=True, max_length=255, null=True)),
                ('bust', models.FloatField()),
                ('waist', models.FloatField()),
                ('hips', models.FloatField()),
                ('length', models.FloatField()),
                ('delivery_date', models.DateField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='dress_references/')),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_custom',
        ),
    ]
