# Generated by Django 5.1.4 on 2025-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0022_customdressorder_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdressorder',
            name='work_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
